sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ankushanubhav/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ankushanubhav/docker-react npm run test
